[language-server.uwu_colors]
command = "uwu_colors"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true
analyses = { unusedparams = true, unreachable = true }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]
roots = ["go.mod", "go.work"]

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["uwu_colors"]

[[language]]
name = "__common__"
scope = "source.__common__"
file-types = []
language-servers = [ "uwu_colors" ]
