[language-server.uwu_colors]
command = "uwu_colors"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true
analyses = { unusedparams = true, unreachable = true }
hints = { assignVariableTypes = true, compositeLiteralFields = true, constantValues = true, functionTypeParameters = true, parameterNames = true, rangeVariableTypes = true, ignoredError = false }


# [language-server.gopls.inlayHints]
# assignVariableTypes = true
# compositeLiteralFields = true
# constantValues = true
# functionTypeParameters = true
# parameterNames = true
# rangeVariableTypes = true
# ignoredError = true
# inlayHints.assignVariableTypes = true
# inlayHints.compositeLiteralFields = true
# inlayHints.constantValues = true
# inlayHints.functionTypeParameters = true
# inlayHints.parameterNames = true
# inlayHints.rangeVariableTypes = true
# inlayHints.ignoredError = true


[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]
roots = ["go.mod", "go.work"]

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["uwu_colors"]

[[language]]
name = "__common__"
scope = "source.__common__"
file-types = []
language-servers = [ "uwu_colors" ]

[[language]]
name = "svg"
scope = ""
roots = []
file-types = ["svg"]
formatter= { command = "svgo", args = ["--pretty", "-"] }

