[language-server.uwu_colors]
command = "uwu_colors"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true
analyses = { unusedparams = true, unreachable = true }
hints = { assignVariableTypes = true, compositeLiteralFields = true, constantValues = true, functionTypeParameters = true, parameterNames = true, rangeVariableTypes = true, ignoredError = false }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]
roots = ["go.mod", "go.work"]

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }
language-servers = ["clangd"]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "eslint",
  "emmet-ls",
]
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "tailwindcss-react",
  "eslint",
  "emmet-ls",
]
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-languageserver"]
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }
auto-format = true


[language-server.vscode-json-languageserver]
args = ["--stdio"]
command = "vscode-json-languageserver"

[language-server.vscode-json-languageserver.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.emmet-ls]
args = ["--stdio"]
command = "emmet-language-server"

[language-server.eslint]
args = ["--stdio"]
command = "eslint"

[language-server.eslint.config]
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = false } }
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
experimental = {}
problems = { shortenToSingleLine = false }



[[language]]
name = "toml"
auto-format = true
language-servers = ["uwu_colors"]

[[language]]
name = "__common__"
scope = "source.__common__"
file-types = []
language-servers = [ "uwu_colors" ]

[[language]]
name = "svg"
scope = ""
roots = []
file-types = ["svg"]
formatter= { command = "svgo", args = ["--pretty", "-"] }

