[language-server.uwu_colors]
command = "uwu_colors"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true
analyses = { unusedparams = true, unreachable = true }
hints = { assignVariableTypes = true, compositeLiteralFields = true, constantValues = true, functionTypeParameters = true, parameterNames = true, rangeVariableTypes = true, ignoredError = false }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]
roots = ["go.mod", "go.work"]

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }
language-servers = ["clangd"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["uwu_colors"]

[[language]]
name = "__common__"
scope = "source.__common__"
file-types = []
language-servers = [ "uwu_colors" ]

[[language]]
name = "svg"
scope = ""
roots = []
file-types = ["svg"]
formatter= { command = "svgo", args = ["--pretty", "-"] }

